import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Download, FileText, BarChart3 } from 'lucide-react'
import { format } from 'date-fns'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

import { api } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useLocale } from '@/hooks/useLocale'
import type { PunchSet, DimensionRecord, Occurrence, OccurrenceType, OccurrenceStatus, SetStatus } from '@/types'

// ── CSV ───────────────────────────────────────────────────────────────────────

function exportCSV(filename: string, headers: string[], rows: string[][]) {
  const bom = '\uFEFF'
  const csv = bom + [headers, ...rows].map((r) => r.map((v) => `"${v}"`).join(';')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ── PDF helpers ───────────────────────────────────────────────────────────────

const BRAND_COLOR: [number, number, number] = [240, 89, 34]

// ── Page ──────────────────────────────────────────────────────────────────────

export function ReportsPage() {
  const [activeTab, setActiveTab] = useState<'dimensional' | 'ocorrencias' | 'conjuntos'>('conjuntos')
  const [selectedSetId, setSelectedSetId] = useState<string>('')
  const { t } = useLocale()

  const { data: sets = [] } = useQuery<PunchSet[]>({
    queryKey: ['punch-sets'],
    queryFn: () => api.get('/punch-sets').then((r) => r.data),
  })

  const { data: records = [] } = useQuery<DimensionRecord[]>({
    queryKey: ['dimension-records', selectedSetId],
    queryFn: () => api.get(`/punch-sets/${selectedSetId}/dimension-records`).then((r) => r.data),
    enabled: !!selectedSetId && activeTab === 'dimensional',
  })

  const { data: occurrences = [] } = useQuery<Occurrence[]>({
    queryKey: ['occurrences-all'],
    queryFn: () => api.get('/occurrences').then((r) => r.data),
    enabled: activeTab === 'ocorrencias',
  })

  // ── PDF helpers ─────────────────────────────────────────────────────────────

  function pdfHeader(doc: jsPDF, title: string, subtitle: string) {
    doc.setFillColor(...BRAND_COLOR)
    doc.rect(0, 0, 210, 18, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.text(t.reports.pdfBrand, 14, 8)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text(t.reports.pdfSubtitle, 14, 13.5)

    doc.setTextColor(40, 40, 40)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(title, 14, 27)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(subtitle, 14, 33)
    doc.text(`${t.reports.pdfGenerated}${format(new Date(), "dd/MM/yyyy 'às' HH:mm")}`, 14, 38)
  }

  function pdfFooter(doc: jsPDF) {
    const pages = doc.getNumberOfPages()
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text(t.reports.pdfPage(i, pages), 14, 290)
      doc.text(t.reports.pdfAutoGenerated, 105, 290, { align: 'center' })
    }
  }

  // ── CSV exports ─────────────────────────────────────────────────────────────

  function exportConjuntosCSV() {
    exportCSV(
      `conjuntos_${format(new Date(), 'yyyyMMdd')}.csv`,
      [t.reports.code, t.reports.name, t.reports.csvStatus, t.reports.usefulLife, t.reports.punches, t.reports.csvOccurrences, t.reports.company, t.reports.createdAt],
      sets.map((s) => [s.code, s.name, t.status[s.status], s.usefulValue.toFixed(1), String(s._count.punches), String(s._count.occurrences), s.company.name, format(new Date(s.createdAt), 'dd/MM/yyyy')])
    )
  }

  function exportDimensionalCSV() {
    const rows: string[][] = []
    for (const r of records)
      for (const v of r.values)
        rows.push([format(new Date(r.measuredAt), 'dd/MM/yyyy HH:mm'), v.parameter, String(v.value), v.unit, v.lowerLimit != null ? String(v.lowerLimit) : '', v.upperLimit != null ? String(v.upperLimit) : '', v.isOk ? 'OK' : 'NOK', r.notes ?? ''])
    exportCSV(`dimensional_${format(new Date(), 'yyyyMMdd')}.csv`, [t.reports.date, t.reports.parameter, t.reports.value, t.reports.csvUnit, t.reports.lowerLimit, t.reports.upperLimit, t.reports.csvStatus, t.reports.observations], rows)
  }

  function exportOcorrenciasCSV() {
    exportCSV(
      `ocorrencias_${format(new Date(), 'yyyyMMdd')}.csv`,
      [t.reports.set, t.reports.csvStatus, t.reports.machine, t.reports.product, t.common.description, t.reports.csvResolution, t.reports.openedAt, t.reports.closedAt],
      occurrences.map((o) => [`${o.set.code} - ${o.set.name}`, t.occurrenceType[o.type], t.occurrenceStatus[o.status], o.machine?.name ?? '', o.product?.name ?? '', o.description, o.resolution ?? '', format(new Date(o.openedAt), 'dd/MM/yyyy'), o.closedAt ? format(new Date(o.closedAt), 'dd/MM/yyyy') : ''])
    )
  }

  // ── PDF exports ─────────────────────────────────────────────────────────────

  function exportDimensionalPDF() {
    const selectedSet = sets.find((s) => s.id === selectedSetId)
    const doc = new jsPDF({ orientation: 'landscape' })

    pdfHeader(doc, t.reports.pdfDimensionalTitle, t.reports.pdfDimensionalSubtitle(selectedSet?.code ?? '', selectedSet?.name ?? ''))

    const rows: (string | { content: string; styles: { textColor: [number, number, number] } })[][] = []
    for (const r of records) {
      for (const v of r.values) {
        const statusCell = v.isOk
          ? { content: 'OK', styles: { textColor: [34, 197, 94] as [number, number, number] } }
          : { content: 'NOK', styles: { textColor: [239, 68, 68] as [number, number, number] } }
        rows.push([
          format(new Date(r.measuredAt), 'dd/MM/yyyy HH:mm'),
          v.parameter,
          `${v.value} ${v.unit}`,
          v.lowerLimit != null ? String(v.lowerLimit) : '—',
          v.upperLimit != null ? String(v.upperLimit) : '—',
          statusCell,
          r.notes ?? '—',
        ])
      }
    }

    autoTable(doc, {
      startY: 44,
      head: [[t.reports.pdfDateTime, t.reports.parameter, t.reports.pdfMeasuredValue, t.reports.lowerLimit, t.reports.upperLimit, t.reports.csvStatus, t.reports.observations]],
      body: rows,
      headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
      bodyStyles: { fontSize: 8 },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      columnStyles: { 5: { halign: 'center', fontStyle: 'bold' } },
      margin: { left: 14, right: 14 },
    })

    pdfFooter(doc)
    doc.save(`relatorio_dimensional_${selectedSet?.code}_${format(new Date(), 'yyyyMMdd')}.pdf`)
  }

  function exportOcorrenciasPDF() {
    const doc = new jsPDF({ orientation: 'landscape' })

    pdfHeader(doc, t.reports.pdfOccurrencesTitle, t.reports.pdfOccurrencesSubtitle(occurrences.length))

    autoTable(doc, {
      startY: 44,
      head: [[t.reports.set, t.reports.csvStatus, t.reports.machine, t.reports.product, t.common.description, t.reports.pdfResolution, t.reports.openedAt, t.reports.closedAt]],
      body: occurrences.map((o) => [
        `${o.set.code}\n${o.set.name}`,
        t.occurrenceType[o.type],
        t.occurrenceStatus[o.status],
        o.machine?.name ?? '—',
        o.product?.name ?? '—',
        o.description,
        o.resolution ?? '—',
        format(new Date(o.openedAt), 'dd/MM/yyyy'),
        o.closedAt ? format(new Date(o.closedAt), 'dd/MM/yyyy') : '—',
      ]),
      headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 7.5 },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      columnStyles: {
        0: { cellWidth: 28 },
        5: { cellWidth: 55 },
        6: { cellWidth: 45 },
      },
      margin: { left: 14, right: 14 },
      didDrawCell: (data) => {
        if (data.column.index === 2 && data.section === 'body') {
          const status = occurrences[data.row.index]?.status
          if (status === 'OPEN') data.cell.styles.textColor = [239, 68, 68]
          else if (status === 'MONITORING') data.cell.styles.textColor = [234, 179, 8]
          else if (status === 'CLOSED') data.cell.styles.textColor = [34, 197, 94]
        }
      },
    })

    pdfFooter(doc)
    doc.save(`relatorio_ocorrencias_${format(new Date(), 'yyyyMMdd')}.pdf`)
  }

  function exportConjuntosPDF() {
    const doc = new jsPDF()
    pdfHeader(doc, t.reports.pdfSetsTitle, t.reports.pdfSetsSubtitle(sets.length))

    autoTable(doc, {
      startY: 44,
      head: [[t.reports.code, t.reports.name, t.reports.csvStatus, t.reports.usefulLife, t.reports.punches, t.reports.csvOccurrences, t.reports.company]],
      body: sets.map((s) => [s.code, s.name, t.status[s.status as SetStatus], `${s.usefulValue.toFixed(1)}%`, String(s._count.punches), String(s._count.occurrences), s.company.name]),
      headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
      bodyStyles: { fontSize: 8.5 },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      columnStyles: { 3: { halign: 'center' }, 4: { halign: 'center' }, 5: { halign: 'center' } },
      margin: { left: 14, right: 14 },
    })

    pdfFooter(doc)
    doc.save(`relatorio_conjuntos_${format(new Date(), 'yyyyMMdd')}.pdf`)
  }

  // ── Render ──────────────────────────────────────────────────────────────────

  const tabs = [
    { id: 'conjuntos' as const, label: t.reports.tabSets, icon: BarChart3 },
    { id: 'dimensional' as const, label: t.reports.tabDimensional, icon: FileText },
    { id: 'ocorrencias' as const, label: t.reports.tabOccurrences, icon: FileText },
  ]

  return (
    <div className="p-4 sm:p-6 space-y-5">
      <div>
        <h2 className="text-xl sm:text-2xl font-bold tracking-tight">{t.reports.title}</h2>
        <p className="text-muted-foreground text-sm mt-0.5">{t.reports.subtitle}</p>
      </div>

      <div className="flex gap-2 border-b">
        {tabs.map(({ id, label, icon: Icon }) => (
          <button
            key={id}
            onClick={() => setActiveTab(id)}
            className={`flex items-center gap-2 px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-px ${
              activeTab === id ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'
            }`}
          >
            <Icon className="h-4 w-4" />
            {label}
          </button>
        ))}
      </div>

      {/* ── Conjuntos tab ── */}
      {activeTab === 'conjuntos' && (
        <div className="space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <p className="text-sm text-muted-foreground">{t.reports.setsRegistered(sets.length)}</p>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={exportConjuntosCSV} disabled={sets.length === 0}>
                <Download className="h-4 w-4" /> CSV
              </Button>
              <Button size="sm" onClick={exportConjuntosPDF} disabled={sets.length === 0}>
                <FileText className="h-4 w-4" /> PDF
              </Button>
            </div>
          </div>
          <div className="rounded-xl border overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>{t.reports.code}</TableHead>
                  <TableHead>{t.reports.name}</TableHead>
                  <TableHead>{t.common.status}</TableHead>
                  <TableHead>{t.sets.usefulLife}</TableHead>
                  <TableHead>{t.sets.punches}</TableHead>
                  <TableHead>{t.reports.company}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {sets.length === 0 ? (
                  <TableRow><TableCell colSpan={6} className="text-center py-8 text-muted-foreground">{t.reports.noSets}</TableCell></TableRow>
                ) : sets.map((s) => (
                  <TableRow key={s.id}>
                    <TableCell className="font-mono text-xs">{s.code}</TableCell>
                    <TableCell>{s.name}</TableCell>
                    <TableCell><Badge variant="secondary">{t.status[s.status as SetStatus]}</Badge></TableCell>
                    <TableCell className="tabular-nums">{s.usefulValue.toFixed(1)}%</TableCell>
                    <TableCell>{s._count.punches}</TableCell>
                    <TableCell className="text-muted-foreground text-xs">{s.company.name}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>
      )}

      {/* ── Dimensional tab ── */}
      {activeTab === 'dimensional' && (
        <div className="space-y-4">
          <div className="flex items-center gap-3 flex-wrap">
            <div className="space-y-1.5 flex-1 max-w-sm">
              <Label>{t.reports.selectSet}</Label>
              <Select value={selectedSetId} onValueChange={setSelectedSetId}>
                <SelectTrigger><SelectValue placeholder={t.reports.selectSetPlaceholder} /></SelectTrigger>
                <SelectContent>
                  {sets.map((s) => <SelectItem key={s.id} value={s.id}>{s.code} — {s.name}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            {selectedSetId && (
              <div className="flex gap-2 pt-6">
                <Button size="sm" variant="outline" onClick={exportDimensionalCSV} disabled={records.length === 0}>
                  <Download className="h-4 w-4" /> CSV
                </Button>
                <Button size="sm" onClick={exportDimensionalPDF} disabled={records.length === 0}>
                  <FileText className="h-4 w-4" /> PDF
                </Button>
              </div>
            )}
          </div>
          {selectedSetId ? (
            <div className="rounded-xl border overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>{t.reports.date}</TableHead>
                    <TableHead>{t.reports.parameter}</TableHead>
                    <TableHead>{t.reports.value}</TableHead>
                    <TableHead>{t.reports.lowerLimit}</TableHead>
                    <TableHead>{t.reports.upperLimit}</TableHead>
                    <TableHead>{t.common.status}</TableHead>
                    <TableHead>{t.reports.observations}</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {records.length === 0 ? (
                    <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground">{t.reports.noRecords}</TableCell></TableRow>
                  ) : records.flatMap((r) =>
                    r.values.map((v) => (
                      <TableRow key={v.id}>
                        <TableCell className="text-xs text-muted-foreground whitespace-nowrap">{format(new Date(r.measuredAt), 'dd/MM/yyyy HH:mm')}</TableCell>
                        <TableCell className="text-sm font-mono">{v.parameter}</TableCell>
                        <TableCell className="tabular-nums">{v.value} {v.unit}</TableCell>
                        <TableCell className="text-muted-foreground tabular-nums">{v.lowerLimit ?? '—'}</TableCell>
                        <TableCell className="text-muted-foreground tabular-nums">{v.upperLimit ?? '—'}</TableCell>
                        <TableCell><Badge variant={v.isOk ? 'success' : 'destructive'}>{v.isOk ? 'OK' : 'NOK'}</Badge></TableCell>
                        <TableCell className="text-xs text-muted-foreground max-w-[160px] truncate">{r.notes ?? '—'}</TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          ) : (
            <Card><CardContent className="py-12 text-center text-muted-foreground">{t.reports.selectSetToView}</CardContent></Card>
          )}
        </div>
      )}

      {/* ── Ocorrências tab ── */}
      {activeTab === 'ocorrencias' && (
        <div className="space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <p className="text-sm text-muted-foreground">{t.reports.occurrencesCount(occurrences.length)}</p>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={exportOcorrenciasCSV} disabled={occurrences.length === 0}>
                <Download className="h-4 w-4" /> CSV
              </Button>
              <Button size="sm" onClick={exportOcorrenciasPDF} disabled={occurrences.length === 0}>
                <FileText className="h-4 w-4" /> PDF
              </Button>
            </div>
          </div>
          <div className="rounded-xl border overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>{t.reports.set}</TableHead>
                  <TableHead>{t.common.type}</TableHead>
                  <TableHead>{t.common.status}</TableHead>
                  <TableHead>{t.reports.machine}</TableHead>
                  <TableHead>{t.reports.product}</TableHead>
                  <TableHead>{t.reports.description}</TableHead>
                  <TableHead>{t.reports.openedAt}</TableHead>
                  <TableHead>{t.reports.closedAt}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {occurrences.length === 0 ? (
                  <TableRow><TableCell colSpan={8} className="text-center py-8 text-muted-foreground">{t.reports.noOccurrences}</TableCell></TableRow>
                ) : occurrences.map((o) => (
                  <TableRow key={o.id}>
                    <TableCell>
                      <p className="font-mono text-xs font-medium">{o.set.code}</p>
                      <p className="text-xs text-muted-foreground">{o.set.name}</p>
                    </TableCell>
                    <TableCell><Badge variant="secondary">{t.occurrenceType[o.type as OccurrenceType]}</Badge></TableCell>
                    <TableCell><Badge variant={o.status === 'OPEN' ? 'destructive' : o.status === 'MONITORING' ? 'warning' : 'success'}>{t.occurrenceStatus[o.status as OccurrenceStatus]}</Badge></TableCell>
                    <TableCell className="text-sm text-muted-foreground">{o.machine?.name ?? '—'}</TableCell>
                    <TableCell className="text-sm text-muted-foreground">{o.product?.name ?? '—'}</TableCell>
                    <TableCell className="max-w-[200px] truncate text-sm">{o.description}</TableCell>
                    <TableCell className="text-xs text-muted-foreground whitespace-nowrap">{format(new Date(o.openedAt), 'dd/MM/yyyy')}</TableCell>
                    <TableCell className="text-xs text-muted-foreground whitespace-nowrap">{o.closedAt ? format(new Date(o.closedAt), 'dd/MM/yyyy') : '—'}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>
      )}
    </div>
  )
}
